# Generated by Django 3.1.7 on 2021-04-29 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('youtube_clone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(blank=True, max_length=120)),
                ('like', models.BooleanField(blank=True, default=None, null=True)),
                ('dislike', models.BooleanField(blank=True, default=None, null=True)),
                ('original_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.comment')),
                ('video', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='youtube_clone.video')),
            ],
        ),
    ]
