# Generated by Django 3.1.7 on 2021-04-27 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='video_id',
            new_name='video',
        ),
    ]
