# Generated by Django 3.1.7 on 2021-04-27 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20210426_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_reply',
            field=models.ForeignKey(blank=True, default=None, max_length=120, on_delete=django.db.models.deletion.CASCADE, to='comments.comments'),
        ),
    ]
