# Generated by Django 3.1.7 on 2021-04-27 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_clone', '0005_auto_20210426_1744'),
        ('comments', '0006_auto_20210427_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='video',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='youtube_clone.video'),
        ),
    ]
