# Generated by Django 3.1.7 on 2021-04-27 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_clone', '0005_auto_20210426_1744'),
        ('comments', '0007_auto_20210427_0558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_comment', models.CharField(max_length=120)),
                ('like', models.BooleanField(blank=True, default=None, null=True)),
                ('dislike', models.BooleanField(blank=True, default=None, null=True)),
                ('replies', models.ForeignKey(blank=True, default=None, max_length=120, on_delete=django.db.models.deletion.CASCADE, to='comments.comment')),
                ('video', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='youtube_clone.video')),
            ],
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
