# Generated by Django 3.1.7 on 2021-04-27 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0008_auto_20210427_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='replies',
            field=models.ForeignKey(blank=True, max_length=120, on_delete=django.db.models.deletion.CASCADE, to='comments.comment'),
        ),
    ]
