# Generated by Django 3.1.7 on 2021-04-27 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0009_auto_20210427_0657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='original_comment',
            new_name='comment_text',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='replies',
            new_name='original_comment_id',
        ),
    ]
