# Generated by Django 3.1.7 on 2021-04-27 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0011_auto_20210427_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='original_comment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.comment'),
        ),
    ]
