# Generated by Django 3.1.7 on 2021-04-27 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0012_auto_20210427_0711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='original_comment_id',
            new_name='original_comment',
        ),
    ]
