# Generated by Django 3.1.7 on 2021-04-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('yt_video_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('likes', models.IntegerField(blank=True, default=0, null=True)),
                ('dislikes', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
