# Generated by Django 3.1.7 on 2021-04-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_clone', '0002_auto_20210429_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='yt_video_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
