# Generated by Django 3.1.7 on 2021-04-26 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_clone', '0002_auto_20210426_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='comments',
        ),
    ]
