# Generated by Django 3.1.7 on 2021-04-27 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_clone', '0003_remove_video_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='yt_video_id',
            new_name='yt_video',
        ),
    ]
